### ISSUE TITLE
Training process is too slow

### ISSUE THREAD

**Issue by qinguangming1999** [liyongkang123/HMGCL#1]
Sorry to bother you, I'm traying to reproduce your HMGCL, but the training process is too slow, could you tell me, how llong will the training pricess be.

**Comment by qinguangming1999** [comment]
stuck in backward()

**Comment by liyongkang123** [comment]
hi, I'm not sure about what GPU you are using. For me with V100 32G, A100 40G, A6000 48 G, and A100 80G,  I remember that most data sets can be trained in about two hours. Except for those data sets with the largest amount of data, you can adjust the learning rate and epoch number to speed up training.

**Comment by liyongkang123** [comment]
I must admit that my code is not good enough, it takes up a lot of GPU memory

**Comment by qinguangming1999** [comment]
Thanks, I'll try again with a better GPU, if all goes well, i'll cite your work.

**Comment by liyongkang123** [comment]
Ok, thank you~ If you have any questions, you can leave a message on this issue
